apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-services
  namespace: lyczeq
  labels:
    app.kubernetes.io/name: virtual-services
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |
    {
      "body":[
          {
            "widget": "Table",
            "source": "spec.gateways[]",
            "name": "Gateways",
            "children": [
            {
              "source": "$item",
              "name": "Name",
              "widget": "ResourceLink",
              "resource":{
                "kind": "'Gateway'",
                "name": "$contains(data,'/') ? $substringAfter(data, '/') : $substringBefore(data, '.')",
                "namespace": "$contains(data,'/') ? $substringBefore(data, '/'): $split($substringAfter(data, '.'),'.')[0] "
                # discuss that split -> default ns -> vs have gateways specified in a different way than in the Istio VS docs
              }
            }
            ]
          },
          {
            "name": "Hosts",
            "widget": "Panel",
            "children": [
              {"source": "spec.hosts", "widget": "Labels", "name": "Hosts"},
              {"name": "Export to", "source": "spec.exportTo", "widget": "Labels", "visibility": "$exists(*)"}
            ]
          },
          {
            "widget": "CodeViewer",
            "source": "spec.http",
            "name": "HTTP",
            "visibility": "$exists(*)"
          },        
          {
            "widget": "CodeViewer",
            "source": "spec.tcp",
            "name": "TCP",
            "visibility": "$exists(*)"
          },
          {
            "widget": "CodeViewer",
            "source": "spec.tls",
            "name": "TLS",
            "visibility": "$exists(*)"
          }
      ]
    }
  form: |-
    [
      {
        "path": "spec.tls", "simple": true, "widget": "GenericList", "name": "TLS", "children":[
          {
            "path": "[].match", "simple": true, "widget": "GenericList", "name": "Matches", "children": [

              {
                "path": "[].sourceNamespace", "simple": true, "name": "Source Namespace"
              },
              {
                "path": "[].port", "simple": true, "name": "Port"
              },
              {
                "path": "[].sniHosts", "simple": true, "widget": "SimpleList", "name": "SNI Hosts"
              },
              {
                "path": "[].destinationSubnets", "simple": true, "widget": "SimpleList", "name": "Destination Subnets"
              },
              {
                "path": "[].sourceLabels", "simple": true, "widget": "KeyValuePair", "name": "Source Labels"
              },
              {
                "path": "[].gateways", "simple": true, "widget": "SimpleList", "name": "Gateways"
              },

            ]
          },

          {
            "path": "[].route", "simple": true, "widget": "GenericList", "name": "Routes", "children": [

              {
                "path": "[].weight", "simple": true, "name": "Weight"
              },
              {
                "path": "[].destination", "simple": true, "widget": "FormGroup", "name": "Destination", "children": [

                  {
                    "path": "host", "simple": true, "name": "Host"
                  },
                  {
                    "path": "subset", "simple": true, "name": "Subset"
                  },
                  {
                    "path": "port.number", "simple": true, "name": "Port number"
                  }
                
                ]
              },


            ]
          },
        ]
      },

      {
        "path": "spec.tcp", "simple": true, "name": "TCP", "widget": "GenericList", "children": [

          {
            "path": "[].match", "simple": true, "name": "Matches", "children": [

              {
                "path": "[].sourceNamespace", "simple": true, "name": "Source Namespace"
              },
              {
                "path": "[].port", "simple": true, "name": "Port"
              },
              {
                "path": "[].sniHosts", "simple": true, "widget": "SimpleList", "name": "SNI Hosts"
              },
              {
                "path": "[].destinationSubnets", "simple": true, "widget": "SimpleList", "name": "Destination Subnets"
              },
              {
                "path": "[].sourceLabels", "simple": true, "widget": "KeyValuePair", "name": "Source Labels"
              },
              {
                "path": "[].gateways", "simple": true, "widget": "SimpleList", "name": "Gateways"
              }

            ]
          },

          {
            "path": "[].route", "simple": true, "name": "Routes", "children": [

              {
                "path": "[].weight", "simple": true, "name": "Weight"
              },
              {
                "path": "[].destination", "simple": true, "widget": "FormGroup", "name": "Destination", "children": [

                  {
                    "path": "host", "simple": true, "name": "Host"
                  },
                  {
                    "path": "subset", "simple": true, "name": "Subset"
                  },
                  {
                    "path": "port.number", "simple": true, "name": "Port number"
                  }
                
                ]
              },

            ]
          },

        ]
      },


      {
        "path": "spec.http", "simple": true, "name": "HTTP", "widget": "GenericList","children":[

          {
            "path": "[].route", "simple": true, "name": "Routes", "children": [

              {
                "path": "[].weight", "simple": true, "name": "Weight"
              },
              {
                "path": "[].destination", "simple": true, "widget": "FormGroup", "name": "Destination", "children": [

                  {
                    "path": "host", "simple": true, "name": "Host"
                  },
                  {
                    "path": "subset", "simple": true, "name": "Subset"
                  },
                  {
                    "path": "port.number", "simple": true, "name": "Port number"
                  }
                
                ]
              },

            ]
          },

        ] 
      },


      {
        "path": "spec.hosts", "simple": true , "name": "Hosts", "widget": "SimpleList"
      },
      {
        "path": "spec.gateways", "simple": true, "name": "Gateways", "widget": "SimpleList"
      },
      {
        "path": "spec.exportTo", "name": "Export To", "widget": "SimpleList"
      },
    ]
  list: |-
    [
      { 
        "name": "Hosts",
        "source": "spec.hosts",
        "widget": "JoinedArray"
      },
      { 
        "name": "Gateways",
        "source": "spec.gateways",
        "widget": "JoinedArray"
      },
    ]
  dataSources: |-
    { 
      "gateways":{
        "resource": {
          "kind": "Gateway",
          "group": "networking.istio.io",
          "version": "v1beta1"
        },
      }
    }
  general: |-
    {
      "resource": {
        "kind": "VirtualService",
        "group": "networking.istio.io",
        "version": "v1beta1"
      },
      "urlPath": "lyczeq-vs",
      "category": "Lyczeq",
      "scope": "namespace",
      "description": "{{[VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/)}} describes a configuration that affects traffic routing. ."
    }
