apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-services
  namespace: kube-public
  labels:
    app.kubernetes.io/name: virtual-services
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |
    {
      "body":[
          {
            "widget": "Table",
            "source": "spec.gateways[]",
            "name": "Gateways",
            "children": [
            {
              "source": "$item",
              "name": "Name",
              "widget": "ResourceLink",
              "resource":{
                "kind": "'Gateway'",
                "name": "$contains(data,'/') ? $substringAfter(data, '/') : $substringBefore(data, '.')",
                "namespace": "$contains(data,'/') ? $substringBefore(data, '/'): $split($substringAfter(data, '.'),'.')[0] "
              }
            }
            ]
          },
          {
            "name": "Hosts",
            "widget": "Panel",
            "children": [
              {"source": "spec.hosts", "widget": "Labels", "name": "Hosts"},
              {"name": "Export to", "source": "spec.exportTo", "widget": "Labels", "visibility": "$exists(*)"}
            ]
          },
          {
            "widget": "CodeViewer",
            "source": "spec.http",
            "name": "HTTP",
            "visibility": "$exists(*)"
          },        
          {
            "widget": "CodeViewer",
            "source": "spec.tcp",
            "name": "TCP",
            "visibility": "$exists(*)"
          },
          {
            "widget": "CodeViewer",
            "source": "spec.tls",
            "name": "TLS",
            "visibility": "$exists(*)"
          }
      ]
    }
  form: |-
    [
      {
        "path": "spec.hosts", "simple": true
      },
      {
        "path": "spec.http", "simple": true, "widget": "GenericList"
      },
      {
        "path": "spec.http[].name", "simple": true,
      },
    ]
  list: |-
    [
      { 
        "name": "Hosts",
        "source": "spec.hosts",
        "widget": "JoinedArray"
      },
      { 
        "name": "Gateways",
        "source": "spec.gateways",
        "widget": "JoinedArray"
      },
    ]
  dataSources: |-
    { 
      "gateways":{
        "resource": {
          "kind": "Gateway",
          "group": "networking.istio.io",
          "version": "v1beta1"
        },
      }
    }
  general: |-
    {
      "resource": {
        "kind": "VirtualService",
        "group": "networking.istio.io",
        "version": "v1beta1"
      },
      "urlPath": "lyczeq-vs",
      "category": "Lyczeq",
      "scope": "namespace",
      "description": "{{[VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/)}} describes a configuration that affects traffic routing. ."
    }
