apiVersion: v1
kind: ConfigMap
metadata:
  name: pizzas
  namespace: lyczeq
  labels:
    app.kubernetes.io/name: pizzas
    busola.io/extension: resource
data:
  details: |
    {
      "header": [
        {
          "path": "spec.sauce"
        },
        { "path": "spec.toppings", formula: "$join(data.name, ', ')" }, 
      ],
    "body": [
        {
          "name": "Summary",
          "widget": "Panel",
          "children": [
            { "path": "spec.realization" },
            { "path": "spec.paymentMethod", "widget": "Badge" },
            {
              "name": "State",
              "path": "status.messages[-1:].state",
              "widget": "Badge"
            },
            {
              "name": "Message",
              "path": "status.messages[-1:].message"
            },
            { "path": "spec.toppings", formula: "$join(data.name, ', ')" }, 

          ]
        },
        {
          "name": "topping",
          "path": "spec.toppings",
          "widget": "Table",
          "children": [{ "path": "name" }, { "path": "price" }, { "path": "quantity" }]
        },
        {
          "widget": "ResourceList",
          "path": "$pizzaDeployments",
          "name": "Deployed pizzas"
        },{
          "widget": "ResourceList",
          "path": "$secretRecipe",
          "name": "Pizza's recipe secret"
        },
    {
      "name": "columns",
      "widget": "Columns",
      "children": [
        {
          "name": "Comments",
          "widget": "Panel",
          "children": [ {"path": "spec.comments", "widget": "JoinedArray", "separator": "\n"}]
        },
        {
          "name": "spec.description",
          "widget": "Panel",
          "children": [{ "path": "spec.description" }]
        }
      ]
    }
      ]
    }
  form: |-
    [
      { "path": "spec.description", "widget": "Text" , "simple": true},
      { "path": "spec.paymentMethod", "widget": "Text" , "simple": true},
      { "path": "spec.sauce", "widget": "Text" , "simple": true},
      { "path": "spec.realization", "widget": "Text" , "simple": true},
      { "path": "spec.toppings", "simple": true},
      { "path": "spec.toppings.name", "simple": true},
      { "path": "spec.toppings.price", "simple": true},
      { "path": "spec.toppings.quantity", "simple": true},
      { "path": "spec.comments"},
      {
        "path": "spec.recipeSecret",
        "widget": "Resource",
        "kind": "Secret",
        "scope": "namespace",
        "namespace": "default",
        "version": "v1"
      }
    ]
  list: |-
    [
      { "path": "spec.description" },
      { "path": "spec.realization" }, 
      { "name": "Payment method","path": "spec.paymentMethod", "widget": "Badge" }, 
      { "name": "State", "path": "status.messages[-1:].state", "widget": "Badge" },
      { "path": "spec.toppings", formula: "$reduce(data, function($acc, $item) {$acc + $item.price},0)", "name": "Toppings price" }
    ]
  relations: |-
    {
      "pizzaDeployments": {
        "kind": "Deployment",
        "group": "apis/apps",
        "version": "v1",
        "namespace": "default",
        "selector": "$filter(data, function($item) {$item.metadata.labels.`label-example` = 'pizza'})"
      },
      "secretRecipe":{
        "kind": "Secret",
        "group": "api",
        "version": "v1",
        "namespace": "default",
        "selector": "$filter(data, function($item) {$item.metadata.name = 'pizza-recipe'})"
      }
    }
  resource: |-
    {
      "kind": "Pizza",
      "group": "mykubernetes.acme.org",
      "version": "v1",
      "scope": "namespace"
    }
  schema: |-
    {
      "type": "object",
      "properties": {
        "spec": {
          "description": "Information about our pizza",
          "type": "object",
          "properties": {
            "description": {
              "description": "Pizza desc",
              "type": "string"
            },
            "paymentMethod": {
              "description": "The payment method for our pizza",
              "type": "string",
              "enum": [
                "CARD",
                "CASH"
              ]
            },
            "realization": {
              "description": "The order fulfillment of our pizza",
              "type": "string",
              "enum": [
                "DELIVERY",
                "SELF-PICKUP"
              ]
            },
            "sauce": {
              "description": "The name of the sauce to use on our pizza",
              "type": "string"
            },
            "recipeSecret":{
              "description": "The secret with a  pizza's recipe",
              "type": "string"
            },
            "comments":{
              "description": Additional comments,
              "type": "array",
              "items":{
                "type":"string"
              }
            },
            "toppings": {
              "description": "List of toppings for our pizza",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "The name of the topping",
                    "type": "string"
                  },
                  "price": {
                    "description": "The price of the topping",
                    "type": "number"
                  },
                  "quantity": {
                    "description": "The quantity of the selected topping",
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    }
  translations: |
    en:
      name: Pizza
      category: Lunch
      spec.description: Description
      spec.comments: Comments
      spec.state: State
      spec.realization: Realization
      spec.paymentMethod: Payment Method
      spec.sauce: Sauce
      spec.toppings: Toppings
      spec.recipeSecret: Recipe's secret
      topping.name: Name
      topping.price: Price
      topping.quantity: Quantity
