apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pizza-recipe
  namespace: default
  labels:
    app.kubernetes.io/name: pizza-recipe
  annotations: {}
data:
  topping-1: dG9tYXRvIHNhdWNl
  topping-2: Y2hlZXNl
  topping-3: ZmxvdXI=
  topping-4: d2F0ZXI=
  topping-5: eWVhc3Q=
  topping-6: b2xpdmUgb2ls
